### ISSUE TITLE
Windows version not work on 32 bit system

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#230]
Milan Hokr reported serious problem with 32 bit Windows versions.
(Windows 7 system). 
Version 1.8.0 reports: Could not find platform independent libraries.
Same issue was previously reported by Jakub Riha, it is caused by a bug in 32-bit cygwin, 
where Python set base '/usr' when called from the root directory of the flow123d. 

However, Milan report that is doesn't work even when called out  of the flow123d's root.

Moreover, 1.8.0_master version (which should be fixed) reports '/usr' base as well.
![abs_path_180_master](https://cloud.githubusercontent.com/assets/326204/4994479/b6448526-69b9-11e4-8ffd-8025ef1d8f0b.jpg)
![relative_path_180_master](https://cloud.githubusercontent.com/assets/326204/4994478/b640b14e-69b9-11e4-9bb8-e2ffb6725f82.jpg)
![relative_path_181_master](https://cloud.githubusercontent.com/assets/326204/4994477/b64072b0-69b9-11e4-8cfe-f0bd70bd180b.jpg)

**Comment by x3mSpeedy** [comment]
Done some testing and results indicates that 32bit version from bacula doesn't work correctly (at least on this machine). Packed installer created in 32bit Cygwin on this machine works just fine (out of installation folder and even within).
Would be helpful to test binary that worked on this machine on other machines too.

**32bit from bacula (PATH-ALL_USERS)**
* Out of installation folder **[ERROR]**
```
C:\Windows\system32>flow123d
full program name: /usr/bin/flow123d
full flow prefix: /usr
default py prefix: /usr
Python path: /usr/lib/python27.zip:/usr/lib/python2.7/:/usr/lib/python2.7/plat-cygwin:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload
Python home: /usr:/usr
Python prefix: /usr
Python exec prefix: /usr
Traceback (most recent call last):
  File "/home/Jenkins/jenkins/F123-windows32-release/flow123d/build_tree/lib/python2.7/site.py", line 563, in <module>
  File "/home/Jenkins/jenkins/F123-windows32-release/flow123d/build_tree/lib/python2.7/site.py", line 545, in main
  File "/home/Jenkins/jenkins/F123-windows32-release/flow123d/build_tree/lib/python2.7/site.py", line 278, in addusersitepackages
  File "/home/Jenkins/jenkins/F123-windows32-release/flow123d/build_tree/lib/python2.7/site.py", line 253, in getusersitepackages
  File "/home/Jenkins/jenkins/F123-windows32-release/flow123d/build_tree/lib/python2.7/site.py", line 243, in getuserbase
  File "/home/Jenkins/jenkins/F123-windows32-release/flow123d/build_tree/lib/python2.7/sysconfig.py", line 521, in get_config_var
  File "/home/Jenkins/jenkins/F123-windows32-release/flow123d/build_tree/lib/python2.7/sysconfig.py", line 420, in get_config_vars
  File "/home/Jenkins/jenkins/F123-windows32-release/flow123d/build_tree/lib/python2.7/sysconfig.py", line 299, in _init_posix
IOError: invalid Python installation: unable to open /usr/include/python2.7/pyconfig.h (No such file or directory)
```
            
* installation folder **[ERROR]**
```
C:\Program Files (x86)\Flow123d 1.8.0_master\bin>flow123d
full program name: /usr/bin/flow123d
full flow prefix: /usr
default py prefix: /usr
Python path: /usr/lib/python27.zip:/usr/lib/python2.7/:/usr/lib/python2.7/plat-cygwin:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload
Python home: /usr:/usr
Python prefix: /usr
Python exec prefix: /usr
Traceback (most recent call last):
  File "/home/Jenkins/jenkins/F123-windows32-release/flow123d/build_tree/lib/python2.7/site.py", line 563, in <module>
  File "/home/Jenkins/jenkins/F123-windows32-release/flow123d/build_tree/lib/python2.7/site.py", line 545, in main
  File "/home/Jenkins/jenkins/F123-windows32-release/flow123d/build_tree/lib/python2.7/site.py", line 278, in addusersitepackages
  File "/home/Jenkins/jenkins/F123-windows32-release/flow123d/build_tree/lib/python2.7/site.py", line 253, in getusersitepackages
  File "/home/Jenkins/jenkins/F123-windows32-release/flow123d/build_tree/lib/python2.7/site.py", line 243, in getuserbase
  File "/home/Jenkins/jenkins/F123-windows32-release/flow123d/build_tree/lib/python2.7/sysconfig.py", line 521, in get_config_var
  File "/home/Jenkins/jenkins/F123-windows32-release/flow123d/build_tree/lib/python2.7/sysconfig.py", line 420, in get_config_vars
  File "/home/Jenkins/jenkins/F123-windows32-release/flow123d/build_tree/lib/python2.7/sysconfig.py", line 299, in _init_posix
IOError: invalid Python installation: unable to open /usr/include/python2.7/pyconfig.h (No such file or directory)
```
            
            
**32bit Cygwin (packed on Windows machine PATH-ALL_USERS)**
* Out of installation folder **[CORRECT]**
```
C:\Windows\system32>flow123d
full program name: /usr/bin/flow123d
full flow prefix: /usr
default py prefix: /usr
Python path: /usr/lib/python27.zip:/usr/lib/python2.7/:/usr/lib/python2.7/plat-cygwin:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload
Python home: /usr:/usr
Python prefix: /usr
Python exec prefix: /usr
MPI size: 1
This is Flow123d, version 1.8.0_master revision: jenkins-Flow123d-win32-release-multijob-17
Branch: 1.8.0_master
Build: Jan  5 2015, 11:24:45 flags: (unknown compiler flags)
Fetch URL:  https://github.com/flow123d/flow123d.git
Usage error: The main input file has to be specified through -s parameter.
```     
            
* installation folder **[CORRECT]**
```
C:\Program Files (x86)\Flow123d 1.8.0_master\bin>flow123d
full program name: /usr/bin/flow123d
full flow prefix: /usr
default py prefix: /usr
Python path: /usr/lib/python27.zip:/usr/lib/python2.7/:/usr/lib/python2.7/plat-cygwin:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload
Python home: /usr:/usr
Python prefix: /usr
Python exec prefix: /usr
MPI size: 1
This is Flow123d, version 1.8.0_master revision: jenkins-Flow123d-win32-release-multijob-17
Branch: 1.8.0_master
Build: Jan  5 2015, 11:24:45 flags: (unknown compiler flags)
Fetch URL:  https://github.com/flow123d/flow123d.git
Usage error: The main input file has to be specified through -s parameter.
```

**64bit from bacula (PATH-ALL_USERS)**
* Out of installation folder [CORRECT]
```
C:\Windows\system32>flow123d
full program name: /usr/bin/flow123d
full flow prefix: /usr
default py prefix: /usr
Python path: /usr/lib/python27.zip:/usr/lib/python2.7/:/usr/lib/python2.7/plat-cygwin:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload
Python home: /usr:/usr
Python prefix: /usr
Python exec prefix: /usr
MPI size: 1
This is Flow123d, version 1.8.0_master revision: jenkins-Flow123d-win64-release-multijob-15
Branch: 1.8.0_master
Build: Jan  5 2015, 14:01:53 flags: (unknown compiler flags)
Fetch URL:  https://github.com/flow123d/flow123d.git
Usage error: The main input file has to be specified through -s parameter.
```
* installation folder **[CORRECT]**
```
C:\Program Files (x86)\Flow123d 1.8.0_master\bin>flow123d
full program name: /usr/bin/flow123d
full flow prefix: /usr
default py prefix: /usr
Python path: /usr/lib/python27.zip:/usr/lib/python2.7/:/usr/lib/python2.7/plat-cygwin:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload
Python home: /usr:/usr
Python prefix: /usr
Python exec prefix: /usr
MPI size: 1
This is Flow123d, version 1.8.0_master revision: jenkins-Flow123d-win64-release-multijob-15
Branch: 1.8.0_master
Build: Jan  5 2015, 14:01:53 flags: (unknown compiler flags)
Fetch URL:  https://github.com/flow123d/flow123d.git
Usage error: The main input file has to be specified through -s parameter.
```

**Comment by x3mSpeedy** [comment]
Error might be in Cygwin since in newer version it is not possible to reproduce wrong PWD (using simple application from above). Versions are folowing:
```
CYGWIN_NT-6.1-WOW64 Flow123d 1.7.33-2(0.280/5/3) 2014-11-13 15:45 i686 Cygwin
CYGWIN_NT-6.1 Jakub-PC       1.7.30  (0.272/5/3) 2014-05-23 10:36 i686 Cygwin
```

**Comment by jbrezmorf** [comment]
Seems that error is due to Cygwin version not due to Flow123d problem.
