### ISSUE TITLE
docker issues

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#712]
- [x] Seems that (some) Windows updates switch off virtualization support in BIOS. 
      (Probably Home Edition do not support virtualization and switch it off in BIOS, professional edition ... 	with virtualization support should work fine)

- [x] Jenkins is not triggered by push into dev branches.
- [x] git completion not work (need manual add of .git-completion.bash)
- [x] git pull not work:

```
f501 {master} ~/workspace/f123d-docker$ git pull
ssh: Could not resolve hostname github.com: Temporary failure in name resolution
fatal: Could not read from remote repository.
```
- [x] git gui not work (questionable we want it) NO
- [x] make rules completion not work
- [x] How to do debugging within eclipse? Works, running flow123d out of docker.

  Notes: Seems that flow123d executable runs without problems out of docker as long as the mpich is provided. Then debugging could be done out of docker. Running GDB inside docker still usefull for debugging under windows. See [emdocker](https://github.com/embox/embox/wiki/Emdocker)
- [x] add to devel image: vim, clang, ccache
- [x] How to make symlinks under docker on Windows as host OS? see #717 
- [x] Better organization of YAML files for jenkins configuration.
- [x] is separate repository docker-config necessary? We do git clone out of docker anyway. So even if it is part of flow123d repository we can proceed as this:
1. clone flow123d repo
2. configure build image
3. start container and build and test in it
4. package and publish

Separate repo necessary since it is faster and provides consistent configuration of build images for all branches.

Minor drawback is cloning whole flow123d repo for building libraries. This however is done just sparsely.

**Comment by jbrezmorf** [comment]
- [ ] git completion not work (need manual add of .git-completion.bash)
- [ ] git pull not work:
```
f501 {master} ~/workspace/f123d-docker$ git pull
ssh: Could not resolve hostname github.com: Temporary failure in name resolution
fatal: Could not read from remote repository.
```
- [ ] git gui not work (questionable we want it)
- [ ] How to do debugging within eclipse?

**Comment by jbrezmorf** [comment]
seems that simplejson is missing in the image:
```
2444 ~/workspace/f123d-docker/tests/10_darcy$ ../runtest 
Python 2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609], /usr/bin/python2.7
CWD: /home/jb/workspace/f123d-docker/tests/10_darcy, USER: jb
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jb/workspace/f123d-docker/bin/python/runtest.py", line 11, in <module>
    from scripts.core.base import Paths
  File "/home/jb/workspace/f123d-docker/src/python/scripts/core/base.py", line 15, in <module>
    from simplejson import JSONEncoder
ImportError: No module named simplejson
```

**Comment by jbrezmorf** [comment]
Done.
