### ISSUE TITLE
hanging runtest script

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#825]
```
72e0 {PE_assembly_fix} ~/workspace/flow123d/tests/12_darcy_frac$ ../runtest 20_cude_23d_p0.yaml 
Python 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609], /usr/bin/python3
CWD: /home/jb/workspace/flow123d/tests/12_darcy_frac, USER: jb
--------------------------------------------------------------------------------
Found 1 yaml file/s
Running in LOCAL mode
Running 2 cases (excluding all tags in set ['disabled'])
------------------------------------------------------------
Case 01 of 02
Running: 1 x 12_darcy_frac/20_cude_23d_p0
Done    | elapsed time 0:00:03:866                                              
Exception in thread test-case:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/jb/workspace/flow123d/src/python/scripts/core/threads.py", line 78, in run
    self._run()
  File "/home/jb/workspace/flow123d/src/python/scripts/core/threads.py", line 238, in _run
    if self.stop_on_error and self.current_thread.returncode > 0:
TypeError: unorderable types: NoneType() > int()

Exception in thread runner:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/jb/workspace/flow123d/src/python/scripts/core/threads.py", line 78, in run
    self._run()
  File "/home/jb/workspace/flow123d/src/python/scripts/core/threads.py", line 290, in _run
    if self.stop_on_error and self.returncode > 0:
TypeError: unorderable types: NoneType() > int()

^C
Error: Caught SIGINT! Terminating application in peaceful manner...
```

... possible reason, the ref_out dir doesn't exist.

**Comment by jbrezmorf** [comment]
@janhybs Is this fixed?

**Comment by janhybs** [comment]
Yes @jbrezmorf, cause was when we went from `python2.7` to `python3.5` and `python3.5`'s behaviour is a different, more [here](https://stackoverflow.com/questions/8961005/comparing-none-with-built-in-types-using-arithmetic-operators). Code evaluation was reworked.
